apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
        - name: device-service
          image: vaibhavboppana/edgefleet-device-service:1.3
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: MONITORING_SERVICE_URL
              value: "http://monitoring-service:8001"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
